all: myls mysearch mystat mytail

myls: myls-Darshan.c
	gcc -o myls myls-Darshan.c

mysearch: mysearch-Darshan.c
	gcc -o mysearch mysearch-Darshan.c

mystat: mystat-Darshan.c
	gcc -o mystat mystat-Darshan.c

mytail: mytail-Darshan.c
	gcc -o mytail mytail-Darshan.c
